### ISSUE TITLE
Improve time picker UI in AddLog dialog

### ISSUE THREAD

**Issue by JaredDanielJones** [ShelterPartner/ShelterPartner#298]

**Comment by jacobthejones** [comment]
I'll take this

**Comment by JaredDanielJones** [comment]
@jacobthejones ope I think that's because the firebase testing rule just expired because I just used the default testing rule, so I need to change that. Should work in few minutes

**Comment by JaredDanielJones** [comment]
I'm thinking the manual input mode would be better than the dial mode. On ios at least, it's usually a scroll wheel (slot machine) which feels more natural for me. Have you gotten used to the clock dial thing? 

I'd say slot machine style picker if there's an easy prebuilt one, otherwise default to the manual input mode instead of dial.

Also if you don't already have copilot and want it, let me know because you've done 5 pull requests in the past month and that's one of the perks I have in the readme. I think if I add you to the organization, it'll let me automatically add it to your account but I haven't tried it yet with anyone.

**Comment by jacobthejones** [comment]
I actually prefer the clock input mode by quite a bit - it's only two taps
to have the time set, vs many for the scroll wheel and manual input. It's
probably heavily dependent on the platform the person is using, maybe
there's a way to set it to the native picker based on environment. I can
take a look next time I'm making edits.

I already have Copilot so no need, but thank you. :)
